<div id="lastListWrap">
<div class="blockTitle">
   	<div class="left">
   		<div class="right">Новое на сайте</div>
   	</div>
   </div>
   <div class="inner">
   <ul class="bottomDotted">
<?php 

$lastChildNum = sizeof($this->pages);
$i = 0;
foreach ($this->pages as $t) {
	$date = new Zend_Date($t->date_add, 'ru_RU');	
	$i++;
	$tree = $t->getMapper()->getTree();
	$path = $tree->getTreePathTo($t->id);	
	if ($t->is_cat == 0) {
		$path = $tree->getTreePathTo($t->pid);
		$path = $path.$t->shortcut.'/';
	} else {
		$path = $tree->getTreePathTo($t->id);	
	}
	if ($i == $lastChildNum) $class = ' class="last"';
	else $class = '';
	echo '
		<li'.$class.'>
			<div class="date">'.$date->toString('dd MMMM').'</div>
			<a href="'.$path.'">'.$t->title.'</a>
		</li>';
}

?>   							

 </ul>
 </div>
 </div>