<?php 
echo $this->partial('/subscribe/letter-head.phtml');
$url = 'http://new.ulgov.ru/news/subscribe/confirm/k/'.$this->subscribe->keycode.'/';
?>
<p>Спасибо за Вашу подписку на рассылку сообщений пресс-службы Губернатора и Правительства Ульяновской области.</p> 
<p>Для завершения Вашей подписки, пожалуйста, пройдите по следующей ссылке</p>  
<p><strong><a href="http://new.ulgov.ru/news/subscribe/confirm/k/<?php echo $url; ?>">Подтвердить подписку</a></strong></p>
<p><?php echo $url; ?>Подтвердить подписку</p>