<table border=0 cellpadding=5 style="border-bottom: 4px double black;" width=100%>
	<tr>
		<td style="width:100px">
  			<img src="http://www.ulgov.ru/images/ourgerb.gif" width="100" height="84">
  		</td>
  		<td>
  			<span style="font-weight:bold; font-size:14px;">
  				ПРАВИТЕЛЬСТВО УЛЬЯНОВСКОЙ ОБЛАСТИ<br />
  				ПРЕСС-СЛУЖБА ГУБЕРНАТОРА И ПРАВИТЕЛЬСТВА<br />
  			</span>
  			<span style="font-size:9px;">
  				432001, г. Ульяновск, пл. Ленина, 1-311, тел. (8422) 41-27-60, 
  				<a href=mailto:press@mv.ru>press@mv.ru</a>
  			</span>
  			<br />
  			<span style="font-weight:bold; font-size:14px;">СООБЩЕНИЕ ДЛЯ СМИ</span>
  		</td>
  	</tr>
 </table>