<form class="ifrondForm cpFormRef"	
	action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>"
	enctype="<?php echo $this->escape($this->element->getAttrib('enctype')); ?>" >		
		<table class="lyo">
			<tr>
				<td class="lyo ttl">
					<label for="freTitle"><?php echo $this->element->freTitle->getLabel(); ?>:</label>
				</td>
				<td class="lyo val">
					<?php echo $this->element->freTitle; ?>
				</td>
			</tr>
<?php 
if ($this->element->freSubtitle) {
	echo '<tr>
				<td class="lyo ttl">
					<label for="freSubtitle">'.$this->element->freSubtitle->getLabel().':</label>
				</td>
				<td class="lyo val">
					'.$this->element->freSubtitle.'
				</td>
			</tr>';
}
if ($this->element->freThumb) {
	echo '<tr>
				<td class="lyo ttl">
					<label for="freThumb">'.$this->element->freThumb->getLabel().':</label>
				</td>
				<td class="lyo val">
					'.$this->element->freThumb.'
				</td>
			</tr>';
}
if ($this->element->freExtra1) {
	echo '<tr>
				<td class="lyo ttl">
					<label for="freExtra1">'.$this->element->freExtra1->getLabel().':</label>
				</td>
				<td class="lyo val">
					'.$this->element->freExtra1.'
				</td>
			</tr>';
}
if ($this->element->freExtra2) {
	echo '<tr>
				<td class="lyo ttl">
					<label for="freExtra2">'.$this->element->freExtra2->getLabel().':</label>
				</td>
				<td class="lyo val">
					'.$this->element->freExtra2.'
				</td>
			</tr>';
}
if ($this->element->freExtra3) {
	echo '<tr>
				<td class="lyo ttl">
					<label for="freExtra3">'.$this->element->freExtra3->getLabel().':</label>
				</td>
				<td class="lyo val">
					'.$this->element->freExtra3.'
				</td>
			</tr>';
}
if ($this->element->freExtra4) {
	echo '<tr>
				<td class="lyo ttl">
					<label for="freExtra4">'.$this->element->freExtra4->getLabel().':</label>
				</td>
				<td class="lyo val">
					'.$this->element->freExtra4.'
				</td>
			</tr>';
}
?>			
	
			<tr>
				<td class="lyo ttl">&nbsp;</td>
				<td class="lyo val">
					<?php echo $this->element->fpeSave; ?>
					<span class="ajax" onclick="$('#Ref_Form_Edit').hide();">скрыть</span>
				</td>
			</tr>
		</table>
		<?php echo $this->element->freId; ?>
		<?php echo $this->element->frePid; ?>
		<?php echo $this->element->freRang; ?>
		
	</form>
	