<?php 

$newCal = new Ifrond_Model_Calendar ();

foreach ( $this->activeDates as $t ) {
	$newCal->setLinkForDate('/news/index/date/x/' . $t->p . '/', $t->p);
}

//_p($newCal->getAllLinks());

$newCal->setShowTbodyOnly(true);
$calBody = $newCal->getMonthCalendar ($this->month, $this->year);
$nextMonth = $newCal->getNextMonth($this->month, $this->year);
$prevMonth = $newCal->getPrevMonth($this->month, $this->year);
if ($calBody !== false) {
?>
<div class="blueBox" id="calWrap" >
   	<div class="tr"><div class="tl">
   		<div class="calTtl" >
   			<a href="/news/block/calendar/year/<?php echo $prevMonth['year']; ?>/month/<?php echo $prevMonth['month']; ?>/" id="calPrev">&nbsp;</a>
   			<a href="/news/block/calendar/year/<?php echo $nextMonth['year']; ?>/month/<?php echo $nextMonth['month']; ?>/" id="calNext">&nbsp;</a>
   			<div id="calCurMonth"><?php echo $newCal->getMonthTitle($this->month); ?>, <?php echo $this->year; ?></div>   												
   		</div>
			<table id="calTable">
				<thead id="calWeekdays" >
					<tr>
						<th>Пн.</th>
						<th>Вт.</th>
						<th>Ср.</th>
						<th>Чт.</th>
						<th>Пт.</th>
						<th>Сб.</th>
						<th>Вс.</th>
					</tr>
				</thead>
				<tbody id="calTbody" ><?php echo $calBody; ?></tbody>
			</table>
   	
   	</div></div>
</div>
<div id="calChoose" >
   	<div class="blueBox">
   		<div class="br"><div class="bl">   										
   			<form action="/news/block/calendar/" method="get" id="calMonthYearChanger" >
   				<select name="month" class="texter" id="calMYC_month">
   					<option value="1">январь</option>
   					<option value="2">февраль</option>
   					<option value="3">март</option>
   					<option value="4">апрель</option>
   					<option value="5">май</option>
   					<option value="6">июнь</option>
   					<option value="7">июль</option>
   					<option value="8">август</option>
   					<option value="9">сентябрь</option>
   					<option value="10">октябрь</option>
   					<option value="11">ноябрь</option>
   					<option value="12">декабрь</option>   					
   				</select>   										
   				<select name="year" class="texter" id="calMYC_year" >
<?php
$startYear = 2000;
$endYear = date('Y');
for ($i = $startYear; $i <= $endYear; $i++) {
	if (($i+1) == $this->year) $selected = ' selected';
	else  $selected = '';
	echo '<option value="'.$i.'"'.$selected.'>'.$i.'</option>';
}
?> 				</select>   											
   				<input type="submit" class="submitter" value="&nbsp;" />   											
   			</form>   										
   		</div></div>
   	</div>   									
</div>
								
<?php
} else {
	echo 'Неверный формат запроса';
}

?>