<div class="autoheight" id="refTemplatePanel">
	<ul class="cpRefTemplateList">
	<?php 
	
		foreach ($this->templates as $t) {
			echo '<li><a href="/ref/admin/list/pid/'.$t->id.'/">'.$t->title.'</a></li>';
		}
	
	?>
	</ul>
</div>
<div id="refListPanel" class="autoheight">
</div>
<div class="clear"></div>
<script type="text/javascript">
	setAutoHeight();
	$('#refTemplatePanel ul.cpRefTemplateList a').click(function(event){
		event.stopPropagation();
		var url = $(this).attr('href');
		$('#refListPanel').load(url);
		return false;
		});
</script>