var data = {
	result: <?php echo $this->result['result']; ?>, 
	html: '<?php 
	if ($this->ref != false) {
		$li = $this->partial('/admin/refli.phtml', array('ref' => $this->ref, 'template' => $this->template));
		$li = str_replace("\n", ' ', $li);
		$li = str_replace("\r", ' ', $li);
		echo $li;
	}
			?>', 
	msg: '<?php echo str_replace("'", '"', $this->result['msg']); ?>', 
	id: <?php
	if ($this->ref != false) {
		echo $this->ref->id;
	} else {
		echo 0;
	}
	
	?>
}
