<form class="ifrondForm cpFormUpload"	
	action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>"
	enctype="<?php echo $this->escape($this->element->getAttrib('enctype')); ?>" >		
		<label for="fnfTitle"><?php echo $this->element->fnfTitle->getLabel(); ?>:</label>
		<?php echo $this->element->fnfTitle; ?>
		<label for="fnfFile" style="margin-left:20px;"><?php echo $this->element->fnfFile->getLabel(); ?>:</label> 
		<?php echo $this->element->fnfFile; ?>
		<?php echo $this->element->fnfPid; ?>
		<?php echo $this->element->fnfUpload; ?>		
	</form>
	