<form class="ifrondForm cpFormUpload"	
	action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>" >		
		<label for="fngeTitle"><?php echo $this->element->fngeTitle->getLabel(); ?>:</label>
		<?php echo $this->element->fngeTitle; ?>		
		<?php echo $this->element->fngeId; ?>
		<?php echo $this->element->fngeUpload; ?>		
	</form>
	