<form action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>" >		
		<table class="lyo">
				<tr>
					<td class="lyo ttl">
						<label for="email"><?php echo $this->element->email->getLabel(); ?>:</label>
					</td>
					<td class="lyo val"><?php echo $this->element->email; ?></td>
				</tr>
				<tr>
					<td class="lyo ttl">
						<label for="act"><?php echo $this->element->act->getLabel(); ?>:</label>
					</td>
					<td class="lyo val">
						<?php echo $this->element->act; ?>					
					</td>
				</tr>
				<tr>
					<td class="lyo ttl"></td>
					<td class="lyo val">
						<?php echo $this->element->do; ?>
					</td>
				</tr>
			</table>			
	
	
	
	</form>
	
	
	