<form class="standart large" 
	action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>">	
	
<table class="lyo">
		<tr class="odd">
                <td class="ttl lyo"><label for="<?php echo $this->element->login->getAttrib('id'); ?>"><?php echo $this->element->login->getLabel(); ?></label>:</td>
                <td class="val lyo">                	
                	<?php echo $this->element->login; ?>                	
                </td>
        </tr>
        
        <tr>
                <td class="ttl lyo"><label for="<?php echo $this->element->pwd->getAttrib('id'); ?>"><?php echo $this->element->pwd->getLabel(); ?></label>:</td>
                <td class="val lyo">                	
                	<?php echo $this->element->pwd; ?>                	
                </td>
        </tr>   
        <tr>
                <td class="ttl lyo"><label for="<?php echo $this->element->pwd2->getAttrib('id'); ?>"><?php echo $this->element->pwd2->getLabel(); ?></label>:</td>
                <td class="val lyo">                	
                	<?php echo $this->element->pwd2; ?>                	
                </td>
        </tr>  
        <tr class="odd">
                <td class="ttl lyo"><label for="<?php echo $this->element->email->getAttrib('id'); ?>"><?php echo $this->element->email->getLabel(); ?></label>:</td>
                <td class="val lyo">                	
                	<?php echo $this->element->email; ?>                	
                </td>
        </tr> 
        <tr>               
                <td class="ttl lyo"></td>
                <td class="val lyo"><?php echo $this->element->save; ?></td>
        </tr>
</table>

<?php echo $this->element->id; ?>
<?php echo $this->element->topic; ?>
<?php echo $this->element->lat; ?>
<?php echo $this->element->lng; ?>


</form>
