<?php

echo $this->img;
echo $this->form;

?>
<script type="text/javascript">

$('#News_Form_GalleryEdit').submit(function(evt){
	evt.stopPropagation();	
	form = $(this);
	var errored = 0;
	var inputs = form.serializeObject();
	if (inputs['fngeTitle'].length < 3) {
		erroredInput('#fngeTitle');
		errored = 1;
		alert('Заголовок должен быть длиннее 3 символов');
	}
	if (errored == 0) {		
		inputs = form.serialize();
		var url = form.attr('action');
		$.ajax({
		  url: url,
		  data: inputs,
		  dataType: "json",
		  type: "POST",
		  success: function(data) {
			if (data.result == false) {
				for (var t in data.errors) {
					if ($('#News_Form_Edit').has('#' + t)) {						
						erroredInput('#' + t);
					}
				}						
			} else {
				fillForm('#News_Form_Edit', data.gallery);	
				$('#gallery_' + data.gallery.fngeId + ' img').attr('alt', data.gallery.fngeTitle);			
			}
			if (data.msg != '') alert(data.msg);		
		  }
		});
	}
	
	return false;
});

</script>