<script type="text/javascript" src="/ifrond/js/modules/news/index.js"></script>
<div class="autoheight" id="newsListPanel">
<div class="ui-widget-header ui-corner-all">
<div class="paging" id="newsPageWrap">Страница: <select name="page"
	id="newsPage">
	<?php echo $this->partial('/admin/pageselect.phtml', array('max' => $this->pageCount, 'current' => $this->pageCurrent)); ?>
</select></div>
<ul class="ifrondToolbar">
	<li><span id="newsAdd" class="ss_sprite ss_newspaper_add">&nbsp;</span></li>
	<li><span id="newsEdit" class="ss_sprite ss_newspaper">&nbsp;</span></li>
	<li><span id="newsDelete" class="ss_sprite ss_cross">&nbsp;</span></li>
	<li><span id="newsFilter" class="ss_sprite ss_magnifier">&nbsp;</span></li>
</ul>
</div>
<ul class="cpNewsList" id="cpNewses">
	<?php echo $this->partial('/admin/newslist.phtml', array('news' => $this->news)); ?>
</ul>
</div>
<div id="newsEditPanel" class="autoheight">
	<?php 
		echo $this->form;
	?>
	
	<div class="ui-widget-header ui-corner-all">
		<ul class="ifrondToolbar">
			<li>Фотогалерея</li>
			<li><span id="newsGalleryAdd" class="ss_sprite ss_image_add">&nbsp;</span></li>
			<li><span id="newsGalleryEdit" class="ss_sprite ss_image_edit">&nbsp;</span></li>
			<li><span id="newsGalleryDelete" class="ss_sprite ss_image_delete">&nbsp;</span></li>		
		</ul>
	</div>	
	
	<div id="newsGallery">	
		<?php 
			echo $this->formGallery;
		?>
		<ul id="newsAttImgList" class="cpImageList"></ul>
	</div>
	
</div>
<div class="clear"></div>
<script type="text/javascript">	

	var newsFilter = {};
	newsFilter.fnfTitle = '';
	newsFilter.fnfPid = 0;
	newsFilter.fnfPage = 1;	
	newsFilter.fnfStart = '';
	newsFilter.fnfEnd = '';

	$('#newsPage').change(function(){
		newsFilter.fnfPage = $(this).val();
		updateNewsList();
	});

	function updateNewsList() {		
		$.ajax({
			  url: '/news/admin/list/',
			  data: newsFilter,
			  dataType: "json",
			  type: "POST",
			  success: function(data) {
				if (data.result == false) {
					alert('Ошибочный запрос');					
				} else {
					$('#cpNewses').html(data.news);
					$('#newsPage').html(data.pageSelect);
				}
				if (data.msg != '') alert(data.msg);		
			  }
			});	
	}

	setNewsToolbar();
	setWYSIWYG();
	setAutoHeight();	
	setFormCallback();	

	$('#News_Form_Gallery').ajaxForm({		
		beforeSubmit: function(a,f,o) {			
			$(this).append('<em>Загрузка...</em>');
			if ($('#fnfPid').val() < 1) {
				alert('Сначала нужно сохранить новость');
				return false;
			}
		},
		success: function(data) {		
			eval(data);			
			if (data.result == false) {
				alert(data.msg);
			} else {				
				$('#newsAttImgList').append(data.html);
				$('#newsAttImgList').sortable({distance: 10});
			}
		}		
	}); 
	
	$('#newsGalleryAdd').click(function(){
		if ($('#fnfPid').val() < 1) {
			alert('Сначала нужно сохранить новость');
			return false;
		}
		$('#News_Form_Gallery').toggle();
	});
	
	$('#newsGalleryDelete').click(function(){	
		var sel = $('#newsAttImgList li.ui-selected');
		var id = String(sel.attr('id'));
		id = id.replace('gallery_', '');
		$.getJSON('/news/admin/gallerydelete/', {id: id}, function(data) {
			if (data.result) {
				var galleryLi = $('#gallery_' + data.id);
				if (galleryLi.get(0)) $('#gallery_' + data.id).remove();
			}
			if (data.msg != '') alert(data.msg);			
		});					
	});

	$('#newsGalleryEdit').click(function(){		
		var imageWin = $('#ifrondGalleryEdit').get(0);
		var sel = $('#newsAttImgList li.ui-selected');
		var id = String(sel.attr('id'));
		id = id.replace('gallery_', '');
		if (!imageWin) {
			imageWin = $('<div id="ifrondGalleryEdit">loading...</div>');
			imageWin.load('/news/admin/galleryedit/id/' + id + '/').dialog({
				height: 350,
				width: 550,
				title: 'Переименовать фотографию',
				modal: false,
				zIndex: 300100,
				close: function(event, ui) {
					$(this).dialog( "destroy" );
					$('#ifrondGalleryEdit').remove();
				}
			});	
		} else {
			if (!$('#ifrondGalleryEdit').dialog( "isOpen" )) $('#ifrondGalleryEdit').dialog('open');
		}
	});
	
	$('#newsAttImgList').sortable({distance: 20});
	$('#newsAttImgList').bind( "sortupdate", function(event, ui) {		
		var ul = ui.item.parent();
		var order = ul.sortable("serialize");		
		$.getJSON('/news/admin/rang/', order, function(data) {
			if (data.result == false) alert(data.msg);
		});
	});
	$('#newsAttImgList li').live('click', function(){
		$('#newsAttImgList li').removeClass('ui-selected');
		$(this).addClass('ui-selected');
	});
	$('#newsAttImgList li').live('dblclick', function(){
		var url = $(this).attr('href');
		window.open(url);	
	});	
	$("#cpNewses li .ttl a.ajax").live('click', function(evt){ 
		evt.stopPropagation();
		var url = $(this).attr('href');
		$.getJSON(url, function(data) {
			  if (data.result == false) {
					alert(data.msg);
				} else {
					fillForm('#News_Form_Edit', data.news);					
					$('#fnfPid').val(data.news.fneId);
					$('#newsAttImgList').html(data.gallery);
				}
			});
		return false;
	});	
	$("#cpNewses li").live('click', function(evt){ 
		$("#cpNewses li").removeClass("ui-selected");
		$(this).addClass("ui-selected");
	});	
	$("#cpNewses li").live('dblclick', function(evt){$('.ttl a.ajax', this).click()});
	$("#fneDate").datepicker();	
</script>
