<form class="ifrondForm cpFormUpload"	
	action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>"
	enctype="<?php echo $this->escape($this->element->getAttrib('enctype')); ?>" >	
		<label for="fcfFile"><?php echo $this->element->fcfFile->getLabel(); ?>:</label> <?php echo $this->element->fcfFile; ?>
		<?php echo $this->element->fcfDir; ?>
		<?php echo $this->element->fcfUpload; ?>		
	</form>
	