<?php 
$i = 0;
$photosHtml = '';
$newsHtml = '';
foreach ($this->news as $t) {
	$i++;
	$classPhoto = '';
	$classNews = '';	
	if ($i == 1) {
		$classPhoto = ' class="active"';
		$classNews = ' class="first active"';
	} elseif ($i == 2) {
		$classNews = ' class="second"';
	} elseif ($i == 2) {
		$classNews = ' class="last"';
	}
	$t->extend();
	$photos = $t->getGallery();
	$date = new Zend_Date($t->date_event, 'ru_RU');
	if (sizeof($photos) > 0) {
		$firstPhoto = $photos[0];		
		$thumb = new Ifrond_Model_Thumb(PATH_WEBROOT.$firstPhoto->path);
		$thumb->adaptiveResize(400, 264)->saveQuick();	
		$firstPhotoUrl = $thumb->getThumbUrl();
		$firstPhotoAlt = $firstPhoto->title;
	} else {
		$firstPhotoUrl = '/pub/images/mainnews/nophoto.jpg';
		$firstPhotoAlt = '';
	}
	$newsLink = '/news/'.$t->topic->extra1.'/'.$date->toString('ddMMYYYY').'/'.$t->id.'/';
	$photosHtml .= '<a '.$classPhoto.' id="mn_link_'.$i.'_photo" href="'.$newsLink.'"><img alt="'.$firstPhotoAlt.'" src="'.$firstPhotoUrl.'" /></a>';
	$newsHtml .= '<li '.$classNews.'>
   						<a title="'.clearStr($t->subtitle).'" href="'.$newsLink.'" id="mn_link_'.$i.'">
   							<span class="date">'.$date->toString('d MMMM').'</span>
   							<span class="ttl">'.clearStr($t->title).'</span>
   						</a>   								
   					</li>';
}

?>							
   							<div class="photos"><?php echo $photosHtml;?></div>
   							<ul class="links" ><?php echo $newsHtml;?></ul>