							<div class="blockTitle">
   								<div class="left">
   									<div class="right">
   										<div class="rss"><a href="/news/feed/rss/" >rss-лента</a></div>
   										Пресс-служба
   									</div>
   								</div>
   							</div>
   							
   							<div class="newses">
<?php 

$i = 0;
$dateTitle = '';
foreach ($this->news as $t) {	
	$i++;	
	$t->extend();
	$photos = $t->getGallery();
	$date = new Zend_Date($t->date_event, 'ru_RU');
	$currrentDate = $date->toString('d MMMM');
	if ($dateTitle != $currrentDate) {
		$dateTitle = $currrentDate;
		if ($i != 1) echo '</ul>';
		echo '
			<div class="date">'.$dateTitle.'</div>
			<ul class="newsList bottomDotted">';		
	}
	$photosNum = sizeof($photos);
	if ($photosNum > 0) {
		$photosNum = '<span class="photos">'.$photosNum.' фото</span>';
	} else {
		$photosNum = '';
	}
	$newsLink = '/news/'.$t->topic->extra1.'/'.$date->toString('ddMMYYYY').'/'.$t->id.'/';
	echo '<li>
   			<div class="wrap">	
				<div class="time">'.$date->toString('HH:mm').'</div>
   				<div class="description">
   					<p class="ttl"><a href="'.$newsLink.'">'.clearStr($t->title).'</a></p>
   					<p class="subttl">'.clearStr($t->subtitle).'</p>
   					<p class="extraInfo">
   						'.$photosNum.' 
   						<span class="topic">Рубрика: <a href="/news/'.$t->topic->extra1.'/">'.$t->topic->title.'</a></span>
   					</p>
   				</div>
   			</div>
   			<div class="clear"></div>
   		</li>';

}

?>   							
   								
   								</ul>   								
   							</div>