<?php $values = $this->values; ?>
<p><strong>Дата обращения - <?php echo date('d.m.Y'); ?></strong></p>
<p><strong>Личная информация</strong></p>
<table border="1">
	<tbody>
		<tr>
			<td style="width:150px;">Фамилия</td>
			<td style="width:550px;"><?php echo $values['person_family']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Имя</td>
			<td style="width:550px;"><?php echo $values['person_name']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Отчество</td>
			<td style="width:550px;"><?php echo $values['person_secondname']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Род занятий</td>
			<td style="width:550px;"><?php echo $values['person_occupation']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Ваши социальные льготы</td>
			<td style="width:550px;"><?php echo $values['person_privilege']; ?></td>
		</tr>
	</tbody>
</table>
<p><strong>Контактные данные</strong></p>
<table border="1">
	<tbody>
		<tr>
			<td style="width:150px;">Индекс</td>
			<td style="width:550px;"><?php echo $values['address_index']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Регион</td>
			<td style="width:550px;"><?php echo $values['address_region']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Район Ульяновской области</td>
			<td style="width:550px;"><?php echo $values['address_district']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Почтовый адрес</td>
			<td style="width:550px;"><?php echo $values['address_address']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Электронная почта</td>
			<td style="width:550px;"><?php echo $values['connection_email']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Телефон</td>
			<td style="width:550px;"><?php echo $values['connection_phone']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Факс</td>
			<td style="width:550px;"><?php echo $values['connection_fax']; ?></td>
		</tr>
	</tbody>
</table>
<p><strong>Органы государственной власти, в которые уже обращались с
данным вопросом</strong></p>
<table border="1">
	<tbody>
		<tr>
			<td style="width:150px;">Органы федеральной власти</td>
			<td style="width:550px;"><?php echo $values['power_federal']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Дата обращения</td>
			<td style="width:550px;"><?php echo $values['power_federaldate']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Органы местного самоуправления</td>
			<td style="width:550px;"><?php echo $values['power_local']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Дата обращения</td>
			<td style="width:550px;"><?php echo $values['power_localdate']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Иные органы и организации</td>
			<td style="width:550px;"><?php echo $values['power_other']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Дата обращения</td>
			<td style="width:550px;"><?php echo $values['power_otherdate']; ?></td>
		</tr>
	</tbody>
</table>
<p><strong>Обращение</strong></p>
<table border="1">
	<tbody>
		<tr>
			<td style="width:150px;">Суть вопроса</td>
			<td style="width:550px;"><?php echo $values['msg_topic']; ?></td>
		</tr>
		<tr>
			<td style="width:150px;">Текст запроса</td>
			<td style="width:550px;"><?php echo $values['msg_msg']; ?></td>
		</tr>
	</tbody>
</table>
<p><strong>Прикрепленные файлы</strong></p>
<?php
if (sizeof($this->files) > 0) {
	foreach ($this->files as $t) {
		echo '<p><a href="http://new.ulgov.ru'.$t.'">'.basename($t).'</a></p>';
	}
} else {
	echo 'нет прикрепленных файлов';
}
?>