<?php

foreach ($this->news as $t) {
	$t->extend();	
	echo '<li rel="'.$t->id.'" id="newsLi_'.$t->id.'">
					<div class="attribs">
						<span class="date">'.toFormatDate($t->date_event, 'd.m.y H:i').'</span>
						<span class="topic">'.$t->topic->title.'</span>
					</div>
					<div class="ttl">
						<a class="ajax getone" 
							href="/news/admin/getone/id/'.$t->id.'/" 
							title="'.strip_tags($t->subtitle).'"						
							>'.$t->title.'</a>
					</div>';
	if (sizeof($t->tags) > 0) {
		echo '<div class="tags"><strong>Тэги:</strong> ';
		$tags = array();
		foreach ($t->tags as $t) {
			$tags[] = $t['title'];
		}
		echo implode($tags, ',').'</div>';
	}
	echo '</li>';
}
?>