<?php
$t = $this->page;
if ($t->is_cat) {
	$class = 'cat';
	$toggler = '<a class="tgler" href="/page/admin/childs/pid/'.$t->id.'/"></a>';
} else {
	$class = 'item';
	$toggler = '';
}
$subtitle = str_replace('"', '', strip_tags($t->subtitle));
if ($t->is_active == 0) $class .= ' deleted';
$title = trim($t->title);
if ($title == '') $title = 'Без названия'; 
echo '<li class="'.$class.'" id="page_'.$t->id.'">
			'.$toggler.'
			<a class="page" href="/page/admin/getpage/id/'.$t->id.'/" rel="'.$t->id.'" title="'.$subtitle.'">'.$title.'</a>
			<div class="clear"></div>
		</li>';


?>