<form class="ifrondForm"
	style="padding: 0 10px 0 50px;" 
	action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>" >	
		<p><?php echo $this->element->fpeTitle; ?></p>
		<div class="extra" style="margin-bottom: 15px;" >
			<table class="lyo">
				<tr>
					<td class="lyo ttl">
						<label for="fpePid"><?php echo $this->element->fpePid->getLabel(); ?>:</label>
					</td>
					<td class="lyo val"><?php echo $this->element->fpePid; ?></td>
					<td class="lyo ttl">
						<label for="fpeIscat"><?php echo $this->element->fpeIscat->getLabel(); ?>:</label>
					</td>
					<td class="lyo val"><?php echo $this->element->fpeIscat; ?></td>
				</tr>
			</table>
		</div>	
			<table class="lyo">
				<tr>
					<td class="lyo">
						<label for="fpeSubtitle"><?php echo $this->element->fpeSubtitle->getLabel(); ?>:</label><br />
						<?php echo $this->element->fpeSubtitle; ?>		
					</td>
					<td class="lyo" style="width:300px;">
						<div class="noreq" style="margin-top: 9px;">
						<table class="lyo" >
							<tr>
								<td class="lyo ttl">
									<label for="fpeShortcut"><?php echo $this->element->fpeShortcut->getLabel(); ?>:</label> 
								</td>
								<td class="lyo val">
									<?php echo $this->element->fpeShortcut; ?>			
								</td>
							</tr>
							<tr>
								<td class="lyo ttl">
									<label for="fpeTags"><?php echo $this->element->fpeTags->getLabel(); ?>:</label> 
								</td>
								<td class="lyo val">
									<?php echo $this->element->fpeTags; ?>			
								</td>
							</tr>
						</table>			
						</div>		
					</td>
				</tr>
			</table>
			<?php echo $this->element->fpeId; ?>
			<?php echo $this->element->fpeRang; ?>
			<div style="margin-top: 20px;" >
				<?php echo $this->element->fpeText; ?>
			</div>
			<?php echo $this->element->fpeSeotitle; ?>
			<?php echo $this->element->fpeSeodescription; ?>
			<?php echo $this->element->fpeSeokeywords; ?>
	</form>