<?= $this->doctype() ?>
<html>
<head>
	<?= $this->headTitle() ?>    
	<?= $this->headLink() ?>    
	<?= $this->headMeta() ?>	
	<?= $this->headScript() ?>
</head>
<body>
	<div id="bgPage">
   	<div class="centered">
   		<div id="header">
   			<a href="/" id="logoHead">&nbsp;</a> 	
   			<div class="titles">
   				<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-titles')); ?>   				
   			</div>
   			<div class="utils" >
   				<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-searcher')); ?>
   				<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-flags')); ?>
   				<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-topicos')); ?>   				
   			</div>   			   			
      	</div>      	
      	<div id="mainMenu">
      		<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-mainmenu')); ?>
      	</div>
      	<table class="lyo" id="carcas">
      		<tbody>
   				<tr>
   					<td class="lyo extra" >
   						<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-leftmenu')); ?>   						
   						<?php echo $this->action('topics', 'block', 'news'); ?>
   						<?php echo $this->action('calendar', 'block', 'news'); ?>
   					</td> 
   					<td class="lyo main" >
   						<div id="content"><?php echo $this->layout()->content; ?></div>
   					</td>
   				</tr>
   			</tbody>
      	</table>      	    	
      </div>
	   <div id="footer" >
	   	<div class="centered">
	      	<table class="lyo">
	      		<tbody>
	      			<tr>
	      				<td class="lyo footmenu">
	      					<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-footmenu')); ?>
	      				</td>
	      				<td class="lyo contacts">
	      					<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-footcontacts')); ?>
	      				</td>
	      				<td class="lyo about">
	      					<?php echo $this->action('include', 'index', 'block', array('script' => 'ulg-footabout')); ?>
	      				</td>
	      			</tr>
	      		</tbody>
	      	</table>
	      </div>
		</div>      	
   </div>
</body>
</html>