<?php 
$name = $this->element->getName();
$img = $this->element->getAttrib('preview');
if ($this->element->isRequired()) {
	$class = ' class="required"';
} else {
	$class = '';
}
?>
<dt id="<?php echo $name; ?>-label"><label for="<?php echo $name; ?>" <?php echo $class; ?>><?php echo $this->element->getLabel(); ?></label></dt>
<dd id="<?php echo $name; ?>-element">
<div id="<?php echo $name; ?>-image"><img src="<?php echo $img; ?>" /></div>
<?php echo $this->content; ?>
<p class="description"><?php echo $this->element->getDescription(); ?></p></dd>
