<h1><?php echo $this->topic->title; ?></h1> 
<?php
if ($this->topic->id == 8) { 
	echo $this->action('getone', 'index', 'block', array('name' => 'hotline'));
}	
echo $this->partial('/index/list.phtml', array('newsList' => $this->newsList));
echo $this->partial('/index/pagination.phtml', array(
	'pageAll' => $this->pageAll, 
	'page' => $this->page,
	'url' => '/news/'.$this->topic->extra1.'/')
);
?>