								<div id="subscribe">
   										<div class="blockTitle">
   											<div class="left">
   												<div class="right">Рассылка</div>
   											</div>
   										</div>   										
   										<div class="blueBox" >
   											<div class="bl" ><div class="br" >
   												<form action="/news/subscribe/do/" method="post" id="emailSubs">
   														<input type="text" name="email" value="ваш e-mail" class="texter" />
   														<input type="submit" name="act" value="1" class="submitter" />
   														<input type="submit" name="act" value="2" class="reseter" />
   												</form>												
   											</div></div>
   										</div> 
   									</div>