<ul id="linkTape" class="bottomDotted" >  	
  	<li>  		
		<img src="/pub/images/linkTape/gosuslugi.jpg" width="23" height="23" />
		<p><a href="http://gosuslugi.ulgov.ru/web/guest/main" >Портал государственных услуг</a></p>		
		<div class="clear" ></div>
	</li>  				
	<li>
		<img src="/pub/images/linkTape/video.jpg" width="23" height="23" />
		<p><a href="/epress/video/" >On-line трансляция</a></p>
		<div class="clear" ></div>
	</li>
	<li>
		<img src="/pub/images/linkTape/kadrrezerv.jpg" width="23" height="23" />
		<p><a href="http://kadr.ulgov.ru/uprkadrrezerv/27/" >Кадровый резерв</a></p>
		<div class="clear" ></div>
	</li>
	<li>
		<img src="/pub/images/linkTape/gospeople.jpg" width="23" height="23" />
		<p><a href="http://kadr.ulgov.ru/101/" >Государственные люди Ульяновской области</a></p>
		<div class="clear" ></div>
	</li>
	<li>
		<img src="/pub/images/linkTape/sites.jpg" width="23" height="23" />
		<p><a href="/epress/ullinks/" >Сайты исполнительных органов государственной власти Ульяновской области</a></p>
		<div class="clear" ></div>
	</li>
  	<li>
		<img src="/pub/images/linkTape/admref.jpg" width="23" height="23" />
		<p><a href="http://admref.ulgov.ru/" >Административная реформа</a></p>
		<div class="clear" ></div>
	</li>
	<li>
		<img src="/pub/images/linkTape/anticrises.jpg" width="23" height="23" />
		<p><a href="/society/4c6a1e181de37/" >Ведение регистра муниципальных НПА Ульяновской области</a></p>
		<div class="clear" ></div>
	</li>
  	<li>
		<img src="/pub/images/linkTape/pnp.jpg" width="23" height="23" />
		<p><a href="http://pnp.ulgov.ru/" >Приоритетные национальные проекты</a></p>
		<div class="clear" ></div>
	</li>
  	<li>
		<img src="/pub/images/linkTape/reglament.jpg" width="23" height="23" />
		<p><a href="/gov/admreg/ad/" >Административные регламенты</a></p>
		<div class="clear" ></div>
	</li>
	<li>
		<img src="/pub/images/linkTape/mpol.jpg" width="23" height="23" />
		<p><a href="http://mp.ulgov.com/" >Молодёжное Правительство</a></p>
		<div class="clear" ></div>
	</li>
  	<li>
		<img src="/pub/images/linkTape/claster.jpg" width="23" height="23" />
		<p><a href="/about/nuclear/" >Ядерно-инновационный кластер</a></p>
		<div class="clear" ></div>
	</li>
  	<li>
		<img src="/pub/images/linkTape/summer.jpg" width="23" height="23" />
		<p><a href="/society/summer/" >Летний оздоровительный отдых детей - 2010</a></p>
		<div class="clear" ></div>
	</li>
  	<li class="last" >
		<img src="/pub/images/linkTape/gosuslugi.jpg" width="23" height="23" />
		<p><a href="http://www.acmoul.narod.ru/" >Совет муниципальных образований</a></p>
		<div class="clear" ></div>
	</li>
</ul>