						<p><strong>О сайте</strong>
							<br /><a href="/epress/aboutsite/rinfos/">официальные банеры</a>
							<br /><a href="/epress/aboutsite/4b619d1799386/">технические сведения</a>
							<br /><a href="/news/site/">новости сайта</a>							
						</p>
      					<p><strong>Сопровождение сайта:</strong>
							<br /><a href="mailto:info@ulgov.ru">администратор сайта</a>
							<br /><a href="http://ifrond.com/">based on iFrond</a></p>						