<form class="ifrondForm cpFormNews"	
	action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>"
	enctype="<?php echo $this->escape($this->element->getAttrib('enctype')); ?>" >		
		<table class="lyo">
				<tr>
					<td class="lyo ttl">
						<label for="fnfPid"><?php echo $this->element->fnfPid->getLabel(); ?>:</label>
					</td>
					<td class="lyo val"><?php echo $this->element->fnfPid; ?></td>
				</tr>
				<tr>
					<td class="lyo ttl">
						<label for="fnfStart"><?php echo $this->element->fnfStart->getLabel(); ?>:</label>
					</td>
					<td class="lyo val">
						<?php echo $this->element->fnfStart; ?>	
						<label for="fnfEnd"><?php echo $this->element->fnfEnd->getLabel(); ?>:</label>	
						<?php echo $this->element->fnfEnd; ?>					
					</td>
				</tr>
				<tr>
					<td class="lyo ttl">
						<label for="fnfTitle"><?php echo $this->element->fnfTitle->getLabel(); ?>:</label>
					</td>
					<td class="lyo val"><?php echo $this->element->fnfTitle; ?></td>
				</tr>
				<tr>
					<td class="lyo ttl"></td>
					<td class="lyo val">
						<?php echo $this->element->fnfSave; ?>
						<?php echo $this->element->fnfPage; ?>
					</td>
				</tr>
			</table>			
	
	
	
	</form>
	
	
	