<?php $ulid = 'files'.md5($this->dir); ?>

<ul style="float:left;padding:0;" class="ifrondToolbar" id="ifrondMCEFileToolbar" >
	<li>Выберите файл</li>
	<li class="ico"><a href="#" id="ifrondMCEFile_Accept" class="ss_sprite ss_application_accept"></a></li>	
	<li class="ico"><a href="#" id="ifrondMCEFile_Add" class="ss_sprite ss_application_add"></a></li>		
	<li class="ico"><a href="#" id="ifrondMCEFile_Delete" class="ss_sprite ss_application_delete"></a></li>
</ul>
<?php 
echo $this->form;
echo '<ul class="cpFileList" id="'.$ulid.'">';
foreach ($this->files as $t) {	
	$alt = str_replace(PATH_WEBROOT, '', $t['path']);
	$alt = str_replace('\\', '/', $alt);
	echo '<li id="'.basename($t['path']).'" rel="'.$this->pmodule.'">'
		.basename($t['path'])
		.' <a href="'.$alt.'" target="_blank" title="скачать">&nbsp;</a></li>';
} 
?>

<script type="text/javascript">

	function insertFile(src) {		
		var ed = $('#fpeText').tinymce();
		var t = ed.selection.getContent({format : 'text'}); 
		if (t == '') t = src.replace(/\\/g,'/').replace( /.*\//, '' );
		ed.selection.setContent('<a href="' + src + '">' + t + '</a>');
		ed.selection.setContent('<strong>' + ed.selection.getContent({format : 'text'}) + '</strong>');
	}
	$('#ifrondMCEFileToolbar').appendTo('#ui-dialog-title-ifrondMCEFile');	
	$('#cpFileUpload').ajaxForm({
		dataType: 'html',
		beforeSubmit: function(a,f,o) {			
			$(this).append('<em>Загрузка...</em>');
		},
		success: function(data) {			
			eval(data);					
			if (data.result == false) {
				alert(data.msg);
			} else {				
				$('#<?php echo $ulid; ?>').prepend(data.html);
				console.log(data.html);
			}
		}		
	}); 
	$('#<?php echo $ulid; ?>').selectable();
	
	$('#<?php echo $ulid; ?> li').live('dblclick', function(){
		var src = $(this).find('a').attr('href');		
		insertFile(src);
		});

	$('#ifrondMCEFile_Accept').live('click', function(event){		
		event.stopPropagation();		
		if ($('#<?php echo $ulid; ?> li.ui-selected').get(0)) {
			$('#<?php echo $ulid; ?> li.ui-selected').each(function(){
				var src = $(this).find('a').attr('href');
				insertFile(src);
			});
			$('#fpeText').focus();
			$('#ifrondMCEImage').dialog('close');
		} else {
			alert('Вы не выбрали файл');
		}
		return false;		
	});

	$('#ifrondMCEFile_Add').live('click', function(event){		
		event.stopPropagation();
		$('#cpFileUpload').slideToggle();
		return false;		
	});

	$('#ifrondMCEFile_Delete').live('click', function(event){		
		event.stopPropagation();
		if ($('#<?php echo $ulid; ?> li.ui-selected').get(0)) {
			$('#<?php echo $ulid; ?> li.ui-selected').each(function(){
				var id = $(this).attr('id');
				var pm = $(this).attr('rel');
				$.getJSON("/cp/file/delete/", {pmodule: pm, filename: id}, function(json){
					   if (json.result) {
						   $('#' + json.id).remove();
					   }
					   else alert(json.msg);
					 });
			});			
		} else {
			alert('Вы не выбрали файл');
		}
		return false;		
	});
	
</script>


