<?php $ulid = 'images'.md5($this->dir); ?>
<script type="text/javascript">

	function insertImage(src) {
		$('#fpeText').tinymce().selection.setContent('<img src="' + src + '" />');
	}
	$('#ifrondMCEImageToolbal').appendTo('#ui-dialog-title-ifrondMCEImage');	
	$('#cpFileUpload').ajaxForm({		
		beforeSubmit: function(a,f,o) {			
			$(this).append('<em>Загрузка...</em>');
		},
		success: function(data) {		
			eval(data);			
			if (data.result == false) {
				alert(data.msg);
			} else {				
				$('#<?php echo $ulid; ?>').prepend(data.html);
				//console.log(data.html);
			}
		}		
	}); 
	$('#<?php echo $ulid; ?>').selectable();
	$('#<?php echo $ulid; ?> li').live('dblclick', function(){
		var src = $(this).find('img').attr('alt');		
		insertImage(src);
		});

	$('#ifrondMCEImage_Accept').live('click', function(event){		
		event.stopPropagation();
		if ($('#<?php echo $ulid; ?> li.ui-selected').get(0)) {
			$('#<?php echo $ulid; ?> li.ui-selected').each(function(){
				var src = $(this).find('img').attr('alt');
				insertImage(src);
			});
			$('#fpeText').focus();
			$('#ifrondMCEImage').dialog('close');
		} else {
			alert('Вы не выбрали изображение');
		}
		return false;		
	});

	$('#ifrondMCEImage_Add').live('click', function(event){		
		event.stopPropagation();
		$('#cpFileUpload').slideToggle();
		return false;		
	});

	$('#ifrondMCEImage_Delete').live('click', function(event){		
		event.stopPropagation();
		if ($('#<?php echo $ulid; ?> li.ui-selected').get(0)) {
			$('#<?php echo $ulid; ?> li.ui-selected').each(function(){
				var id = $(this).attr('id');
				var pm = $(this).attr('rel');
				$.getJSON("/cp/image/delete/", {pmodule: pm, filename: id}, function(json){
					   if (json.result) {
						   $('#' + json.id).remove();
					   }
					   else alert(json.msg);
					 });
			});			
		} else {
			alert('Вы не выбрали изображение');
		}
		return false;		
	});
	
</script>
<ul style="float:left;padding:0;" class="ifrondToolbar" id="ifrondMCEImageToolbal" >
	<li>Выберите изображение</li>
	<li class="ico"><a href="#" id="ifrondMCEImage_Accept" class="ss_sprite ss_image_accept"></a></li>	
	<li class="ico"><a href="#" id="ifrondMCEImage_Add" class="ss_sprite ss_image_add"></a></li>		
	<li class="ico"><a href="#" id="ifrondMCEImage_Delete" class="ss_sprite ss_image_delete"></a></li>
</ul>
<?php 
echo $this->form;
echo '<ul class="cpImageList" id="'.$ulid.'">';
foreach ($this->images as $t) {	
	$alt = str_replace(PATH_WEBROOT, '', $t['path']);
	$alt = str_replace('\\', '/', $alt);
	echo '<li id="'.basename($alt).'" rel="'.$this->pmodule.'">'.$t['thumb']->getImageAsTag(array('alt' => $alt)).'</li>';
} 
?>
</ul>



