<form 
	action="<?php echo $this->escape($this->element->getAction()); ?>" 
	method="<?php echo $this->escape($this->element->getMethod()); ?>"
	id="<?php echo $this->escape($this->element->getAttrib('id')); ?>"	>
	<table class="lyo">
		<tbody>
			<tr>
				<td class="lyo query">
					<?php echo $this->element->query->getLabel(); ?><br />
					<?php echo $this->element->query; ?>
				</td>
				<td class="lyo module">
					<?php echo $this->element->module->getLabel(); ?><br />
					<?php echo $this->element->module; ?>
				</td>
				<td class="lyo period">
					<?php echo $this->element->period->getLabel(); ?><br />
					<?php echo $this->element->period; ?>
				</td>
				<td class="lyo submit">					
					<?php echo $this->element->find; ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
	
	
	