<h2>Редактировать блок <?php echo $this->block->title; ?></h2>
<?php echo $this->form; ?>
<script type="text/javascript">
$('#Block_Form_Edit .wysiwyg').tinymce({		
		document_base_url : "/",		
		relative_urls : false,
		script_url : '/ifrond/js/tiny_mce/tiny_mce.js',
		language: 'ru',
		skin : "o2k7",
		// General options
		theme : "advanced",		
		plugins : "style,table,advimage,advlink,paste,inlinepopups,media,fullscreen",
		// Theme options
		theme_advanced_buttons1 : "undo,redo,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,sub,sup,|,bullist,numlist,|,outdent,indent,blockquote,|,link,unlink,hr,image,media,|,removeformat,cleanup,code,fullscreen",		
		theme_advanced_buttons2 : "pastetext,pasteword,styleselect,formatselect,|,tablecontrols,|,ifrondimage,ifrondfile,ifrondseo",
		theme_advanced_buttons3 : "",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,
		dialog_type : "modal",
		content_css : "/ifrond/css/wisiwyg.css",
		convert_fonts_to_spans : true,
		cleanup_on_startup : true,
		cleanup: true,		
		ifrond_image_url: "/cp/image/index/pmodule/block/",
		ifrond_file_url: "/cp/file/index/pmodule/block/",		
		setup : function(ed) {			
			ed.addButton('ifrondimage', {
				title : 'Вставить изображение',			
				image : '/ifrond/css/images/mce/image.png',
				onclick : function() {
					var id = ed.editorId;
					var form = ed.formElement;	
					var imageWin = $('#ifrondMCEImage').get(0);
					//console.log($('#ifrondMCEImage'));
					if (!imageWin) {
						imageWin = $('<div id="ifrondMCEImage">loading...</div>');
						imageWin.load(ed.settings.ifrond_image_url).dialog({
							height: 350,
							width: 550,
							modal: false,
							zIndex: 300100,
							title: '',
							close: function(event, ui) {
								$(this).dialog( "destroy" );
								$('#ifrondMCEImage').remove();
							}
						});	
					} else {
						if (!$('#ifrondMCEImage').dialog( "isOpen" )) $('#ifrondMCEImage').dialog('open');
					}
								
					
				}
			});
			ed.addButton('ifrondfile', {
				title : 'Загрузить файл',			
				image : '/ifrond/css/images/mce/file.png',
				onclick : function() {
					var id = ed.editorId;
					var form = ed.formElement;	
					var fileWin = $('#ifrondMCEFile').get(0);
					if (!fileWin) {
						fileWin = $('<div id="ifrondMCEFile">loading...</div>');
						fileWin.load(ed.settings.ifrond_file_url).dialog({
							height: 350,
							width: 550,
							modal: false,
							zIndex: 300100,
							title: '',
							close: function(event, ui) {
								$(this).dialog( "destroy" );
								$('#ifrondMCEFile').remove();
							}
						});	
					} else {
						if (!$('#ifrondMCEFile').dialog( "isOpen" )) $('#ifrondMCEFile').dialog('open');
					}
				}
			});	
			
		}
	});

$('#Block_Form_Edit').ajaxForm({
	dataType: 'html',	
	success: function(data) {		
		eval(data);		
		if (data.result == false) {
			alert(data.msg);
		} else {	
			var id = '#block_' + data.id;
			var li = data.html;
			if ($(id).get(0)) {
				$(id).click();
			}			
		}
	}		
});

</script>