<div class="autoheight" id="blockListPanel">
	<ul class="cpBlockList" id="blockList">
	<?php 
	
		foreach ($this->blocks as $t) {
			echo '<li><a href="/block/admin/edit/id/'.$t->id.'/" id="block_'.$t->id.'">'.$t->title.'</a></li>';
		}
	
	?>
	</ul>
</div>
<div id="blockEditPanel" class="autoheight">
</div>
<div class="clear"></div>
<script type="text/javascript">
	setAutoHeight();
	$('#blockList a').click(function(event){
		event.stopPropagation();
		var url = $(this).attr('href');
		$('#blockEditPanel').load(url);
		return false;
		});
</script>