<div class="ui-widget-header ui-corner-all">
<ul class="ifrondToolbar">
	<li><span id="refAdd" class="ss_sprite ss_report_add">&nbsp;</span></li>
	<li><span id="refEdit" class="ss_sprite ss_report_edit">&nbsp;</span></li>
	<li><span id="refDelete" class="ss_sprite ss_cross">&nbsp;</span></li>
</ul>
</div>
<div class="autoheightInner" id="refListPanelInner">
<div id="wrapFormRefAdd"><?php echo $this->form; ?></div>
<ul class="cpRefList" id="refUlList" rel="<?php echo $this->pid; ?>">
<?php
foreach ($this->refs as $t) {
	echo $this->partial('/admin/refli.phtml', array('ref' => $t, 'template' => $this->template));
}
?>
</ul>
</div>
<script type="text/javascript">

setAutoHeight();

$("#refUlList li").live('click', function(){	
	$("#refUlList li").removeClass('ui-selected');
	$(this).addClass('ui-selected');
});

$("#refUlList li").live('dblclick', function(){	
	$(this).find('a.edit').click();
});

$('#refUlList').sortable({distance: 10});

$('#refAdd').click(function(){	
	$('#refListPanelInner')[0].scrollTop = 0;
	$('#wrapFormRefAdd').append($('#Ref_Form_Edit'));
	$('#Ref_Form_Edit').show();
	$('#freTitle').val('');	
	$('#freRang').val('-1');
	$('#freId').val('0');
	if ($('#freSubtitle').get(0)) $('#freSubtitle').val('');
	if ($('#freExtra1').get(0)) $('#freExtra1').val('');
	if ($('#freExtra2').get(0)) $('#freExtra2').val('');
	if ($('#freExtra3').get(0)) $('#freExtra3').val('');
	if ($('#freExtra4').get(0)) $('#freExtra4').val('');
	if ($('#freThumb').get(0)) $('#freThumb').val('');	
});

$('#refEdit').click(function(){
	$('#refUlList li.ui-selected').dblclick();
});

$('#refDelete').click(function(){
	$('#refUlList li.ui-selected a.delete').click();
});



$('#refUlList li a.edit').live('click', function(evt){
	evt.stopPropagation()
	var url = $(this).attr('href');
	$(this).parent().parent().append($('#Ref_Form_Edit'));
	$('#Ref_Form_Edit').show(); 
	$.getJSON(url, function(data) {
		//console.log(data);
		var id = '#ref_' + data.id + ' #Ref_Form_Edit';
		if ($(id).get(0)) {	
			$('#freTitle').val(data.title);	
			$('#freRang').val(data.rang);
			$('#frePid').val(data.pid);
			$('#freId').val(data.id);
			if ($('#freSubtitle').get(0)) $('#freSubtitle').val(data.subtitle);
			if ($('#freExtra1').get(0)) $('#freExtra1').val(data.extra1);
			if ($('#freExtra2').get(0)) $('#freExtra2').val(data.extra2);
			if ($('#freExtra3').get(0)) $('#freExtra3').val(data.extra3);
			if ($('#freExtra4').get(0)) $('#freExtra4').val(data.extra4);			
		}		
	});
	return false;	
});

$('#refUlList').bind( "sortupdate", function(event, ui) {		
	var ul = ui.item.parent();
	var pid = ul.attr('rel');
	var order = ul.sortable("serialize");
	order = order + '&pid=' + pid;
	$.getJSON('/ref/admin/rang/', order, function(data) {
	  if (data.result == false) alert(data.msg);
	});
});

$('#refUlList li a.delete').live('click', function(evt){
	evt.stopPropagation()
	var url = $(this).attr('href');	
	$.getJSON(url, function(data) {
		if (data.result == false) {
			alert(data.msg);
		} else {
			var id = '#ref_' + data.id ;
			if ($(id).get(0)) {
				$(id).remove();	
			}
		}				
	});
	return false;	
});



$('#Ref_Form_Edit').ajaxForm({
	dataType: 'html',	
	success: function(data) {	
		eval(data);	
		$('#wrapFormRefAdd').append($('#Ref_Form_Edit'));
		$('#Ref_Form_Edit').hide();
		if (data.result == false) {
			alert(data.msg);
		} else {	
			var id = '#ref_' + data.id;
			var li = data.html;
			if ($(id).get(0)) {
				$(id).replaceWith(li);
			} else {
				$('#refUlList').append(li);
				$('#refListPanelInner')[0].scrollTop = $('#refListPanelInner')[0].scrollHeight;
				$(id).effect('pulsate', {}, 500);
			}	
			//$('#refUlList').append(data.html);			
		}
	}		
});

</script>

