<?php 
$this->headTitle('Панель управления Ifrond', 'PREPEND');
$this->headTitle()->setSeparator(' :: ');
$this->headScript()->setFile('/ifrond/js/jquery/self.js');
$this->headScript()->appendFile('/ifrond/js/jquery/ui.js');
$this->headScript()->appendFile('/ifrond/js/jquery/plugins.js');
$this->headScript()->appendFile('/ifrond/js/modules/cp/index.js');
$this->headLink()->setStylesheet('/ifrond/css/style.css');

?>
<?php echo $this->doctype() ?>
<html>
<head>
	<?php echo  $this->headTitle() ?>    
	<?php echo  $this->headLink() ?>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<?php echo  $this->headScript() ?>
</head>
<body>
	<div id="ifrondCMS">
		<div id="tabsModule">
			<?php echo $this->action('tabs', 'block', 'cp'); ?>
			<!--  
			<div id="tabsModule_General">		
					
				<div class="autoheight">
					<?php echo $this->layout()->content; ?>
				</div>
				
				
			</div>
			-->
		</div>
	
	</div>
</body>
</html>