<?php 
$request = Zend_Controller_Front::getInstance()->getRequest();
$url = analyseUrl($request->getRequestUri());
$active = array();
$active['home'] = '';
$active['feedback'] = '';
$active['map'] = '';

if (sizeof($url) == 0) {
	$active['home'] = ' active';
} else {
	$active['home'] = '';
}
if (isset($url[0]) && $url[0] == 'feedback') {
	$active['feedback'] = ' active';
}
if (isset($url[0]) && $url[0] == 'map') {
	$active['map'] = ' active';
}
//_p($active);

?>
				<div class="topIcos">
   					<a href="/" class="home<?php echo $active['home']; ?>">&nbsp;</a>
   					<a href="/feedback/" class="feedback<?php echo $active['feedback']; ?>">&nbsp;</a>
   					<a href="/map/" class="map<?php echo $active['map']; ?>">&nbsp;</a>
   				</div>