						<ul id="leftMenu" class="bottomDotted">
   							<li class="first">
   								<a href="/about/" >Об области</a>
   								<p>общая информация об области</p>
   							</li>
   							<li>
   								<a href="http://www.ul-goszak.ru/" >Гос. закупки</a>
   								<p>областной государственный заказ</p>
   							</li>
   							<li>
   								<a href="http://law.ulgov.ru/" >Законодательство</a>
   								<p>постановления и распоряжения</p>
   							</li>
   							<li>
   								<a href="/feedback/" >Обращения</a>
   								<p>задать вопрос Губернатору</p>
   							</li>
   							<li>
   								<a href="http://ulgov.superjob.ru/" >Государственная и муниципальная служба</a>
   								<p>вакансии и объявления</p>
   							</li>   							
   						</ul>