<a href="http://www.sme.ulgov.ru/gospolit/finpod/gospod_01.html" ><img src="/pub/images/pinfo/gospolitfinpod.jpg" /></a>
<a href="http://www.sme.ulgov.ru/gospolit/finpod/gospod_01.html" ><img src="/pub/images/pinfo/money.jpg" /></a>
<a href="/society/4c45a5de3e435/" ><img src="/pub/images/pinfo/perepis.jpg" /></a>
<a href="http://zakonoproekt2010.ru/" ><img src="/pub/images/pinfo/police.jpg" /></a>