<?php 
$request = Zend_Controller_Front::getInstance()->getRequest();
$url = analyseUrl($request->getRequestUri());
$active = array();
$active['home'] = '';
$active['gubernator'] = '';
$active['gov'] = '';
$active['regions'] = '';
$active['news'] = '';
$active['gpriem'] = '';
$active['goveconom'] = '';
$active['society'] = '';
$active['ginvest'] = '';
$active['contacts'] = '';
$active['budget'] = '';

if (sizeof($url) == 0) {
	$active['home'] = ' class="active first"';
} else {
	$active['home'] = ' class="first"';
}
if (isset($url[0]) && $url[0] == 'gubernator') {
	$active['gubernator'] = ' class="active"';
}
if (isset($url[0]) && $url[0] == 'gov') {
	$active['gov'] = ' class="active"';	
}
if (isset($url[0]) && $url[0] == 'power' && $url[1] = 'regions') {
	$active['regions'] = ' class="active"';
}
if (isset($url[0]) && $url[0] == 'news') {
	$active['news'] = ' class="active"';
}
if (isset($url[0]) && $url[0] == 'gpriem') {
	$active['gpriem'] = ' class="active"';
}
if (isset($url[0]) && $url[0] == 'goveconom') {
	$active['goveconom'] = ' class="active"';
}
if (isset($url[0]) && $url[0] == 'society') {
	$active['society'] = ' class="active"';
}
if (isset($url[0]) && $url[0] == 'ginvest') {
	$active['ginvest'] = ' class="active"';
}
if (isset($url[0]) && $url[0] == 'contacts') {
	$active['contacts'] = ' class="last active"';
} else {
	$active['contacts'] = ' class="last"';
}
if (isset($url[0]) && $url[0] == 'budget') {
	$active['budget'] = ' class="active"';
}


?>
				<ul>	      			
					<li<?php echo $active['home']; ?>><a href="/">Главная</a></li>
	      			<li<?php echo $active['gubernator']; ?>><a href="/gubernator/">Губернатор</a></li>
	      			<li<?php echo $active['gov']; ?>><a href="/gov/">Правительство</a></li>
	      			<li<?php echo $active['regions']; ?>><a href="/power/regions/">Города и районы</a></li>
	      			<li<?php echo $active['news']; ?>><a href="/news/">Пресс-служба</a></li>
	      			<li<?php echo $active['gpriem']; ?>><a href="/gpriem/">Приёмная</a></li>
	      			<li<?php echo $active['goveconom']; ?>><a href="/goveconom/">Экономика</a></li>
	      			<li<?php echo $active['society']; ?>><a href="/society/">Общество</a></li>
	      			<li<?php echo $active['ginvest']; ?>><a href="/ginvest/">Инвестиции</a></li>
	      			<li<?php echo $active['budget']; ?>><a href="/budget/">Бюджет</a></li>
	      			<li<?php echo $active['contacts']; ?>><a href="/contacts/">Контакты</a></li>
	      		</ul>	