<p class="menu">
	<a href="/">Главная</a>  |  <a href="/news/">Новости</a>  |  <a href="/contacts/">Контакты</a>  |  
	<a href="/map/">Карта сайта</a>  |  <a href="/search/">Поиск</a>  |  <a href="/links/">Ссылки</a>  |  
	<a href="/news/feed/rss/">RSS</a>
</p> 
<p>
	<a href="http://eservice.ulgov.ru/feedback/">Ваше мнение о сайте</a>  |  <a href="/epress/aboutsite/4be147264c05f/">Законодательная карта по ФЗ № 8</a>
</p>														
<p>
	Правительство Ульяновской области © 2006-2010 <br />
   Использование материалов сайта без ссылки на источник запрещено
</p>      					
<p><a href="/"><img src="/pub/images/counter.jpg" width="88" height="31" /></a></p>	