				<div class="blockTitle">
					<div class="left">
						<div class="right">Партнеры</div>
					</div>
				</div>
				<div id="partnersLogos" >
					<a href="http://www.rg.ru/" ><img src="/pub/images/partners/rg.jpg" /></a>
					<a href="http://www.ulpravda.ru/" ><img src="/pub/images/partners/ulp.jpg" /></a>
					<a href="http://narodka.com/" ><img src="/pub/images/partners/ng.jpg" /></a>
					<a href="http://reporter73.tv/" ><img src="/pub/images/partners/reporter.jpg" /></a>							
				</div>