<?php
if ($this->pageAll > 1) {

	if ($this->pageAll > 20) {
		if ($this->page > 7) {
			$startPage = $this->page - 4;
			$toHome = '<a href="'.$this->url.'?page=1">1</a> ... ';
		} else {
			$startPage = 1;
			$toHome = '';
		}
		if (($this->pageAll - $this->page) > 7) {
			$endPage = $this->page + 4;
			$toEnd = ' ... <a href="'.$this->url.'?page='.$this->pageAll.'">'.$this->pageAll.'</a>';
		} else {
			$endPage = $this->pageAll;
			$toEnd = '';
		}
	}
	if ($this->page > 1) {
		$prev = '&larr; <a href="'.$this->url.'?page='.($this->page - 1).'">предыдущая</a>';
	} else {
		$prev = '';
	}
	if ($this->page < $this->pageAll) {
		$next = ' <a href="'.$this->url.'?page='.($this->page + 1).'">следующая</a> &rarr;';
	} else {
		$next = '';
	}

	$pagesStr = $toHome;
	for ($i = $startPage; $i <= $endPage; $i++) {
		if ($i == $this->page) {
			$pagesStr .= ' <strong>'.$i.'</strong> ';
		} else {
			$pagesStr .= ' <a href="'.$this->url.'?page='.$i.'">'.$i.'</a> ';
		}
	}
	$pagesStr .=  $toEnd;


?>
<div id="paginator">
	<table class="lyo">
		<tbody>
			<tr>
				<td class="lyo prev"><?php echo $prev;?></td>
				<td class="lyo pages"><?php echo $pagesStr;?></td>
				<td class="lyo next"><?php echo $next;?></td>
			</tr>
		</tbody>
	</table>
</div>
<?php 
} 
?>
